# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '网络封装Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking'
pod 'MJExtension'
  # Pods for 网络封装Demo

end
